name: sesame
description: A set of utils for Dart or flutter applications.
version: 1.0.0
homepage: https://github.com/m11v/sesame
environment:
  sdk: '>=2.18.2 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

